apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app_group }}
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
stringData:
  KEYCLOAK_ADMIN_CLIENT: {{ .Values.auth.keycloak.adminClientId }}
  KEYCLOAK_ADMIN_SECRET: {{ .Values.auth.keycloak.adminClientSecret }}
  DATABASE_PASSWORD: {{ .Values.database.username }}
  DATABASE_USERNAME: {{ .Values.database.password }}
