apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: api-deploy-template
  annotations:
    description: "Deployment Configuration Template for the Condition Library Project"
    tags: "condition, api, python"
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP}
      app-group: met-app
    name: ${APP}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP}
          environment: ${ENV}
          role: api
          app-group: met-app
      spec:
        containers:
        - env:
          - name: DB_USER
            value: ${DB_USER}
          - name: DB_PASSWORD
            value: ${DB_PASSWORD}
          - name: DB_NAME
            value: ${DB_NAME}
          - name: DB_HOST
            value: ${DB_HOST}
          - name: DB_PORT
            value: ${DB_PORT}
          - name: DB_SCHEMA
            value: ${DB_SCHEMA}
          imagePullPolicy: Always
          name: ${APP}
          ports:
          - containerPort: 7860
            protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 75m
              memory: 100Mi
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}
        from:
          kind: ImageStreamTag
          name: ${APP}:${IMAGE_TAG}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP}
      app-group: met-app
    name: ${APP}
  spec:
    ipFamilyPolicy: SingleStack
    ports:
    - name: 7860-tcp
      port: 7860
      protocol: TCP
      targetPort: 7860
    selector:
      app: ${APP}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    name: metapihpa
  spec:
    scaleTargetRef:
      kind: DeploymentConfig
      name: ${APP}
      apiVersion: apps.openshift.io/v1
    minReplicas: 1
    maxReplicas: 1
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP}
      app-group: met-app
    name: ${APP}-web-path
  spec:
    host: condition-lib-${ENV}.apps.gold.devops.gov.bc.ca
    path: /api
    port:
      targetPort: 7860-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APP}
      weight: 100
    wildcardPolicy: None
parameters:
  - name: APP
    description: "The application name"
    required: true
    value: condition-lib-web
  - name: IMAGE_NAMESPACE
    description: "The image stream location namespace"
    required: true
    value: c72cba-tools
  - name: ENV
    description: "The selected environment (dev, test, prod)"
    required: true
    value: dev
  - name: DB_HOST
    description: "The postgresql host"
    required: true
    value: met-patroni
  - name: DB_USER
    description: "The postgresql user name"
    required: true
    value: condition
  - name: DB_PASSWORD
    description: "The postgresql user password"
    required: true
    value: condition
  - name: DB_NAME
    description: "The postgresql database name"
    required: true
    value: app
  - name: DB_SCHEMA
    description: "The postgresql database schema"
    required: true
    value: condition
  - name: DB_PORT
    description: "The postgresql database port"
    required: true
    value: '5432'
  - name: IMAGE_TAG
    description: "The image tag to deploy"
    required: true
    value: latest