apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "VITE_ENV": "dev",
        "VITE_API_URL": "{{ .Values.app.api }}",
        "VITE_VERSION": "1.0.0",
        "VITE_APP_TITLE": "Condition Repository",
        "VITE_APP_URL": "{{ .Values.app.url }}",
        "VITE_OIDC_AUTHORITY": "{{ .Values.keycloak.url }}",
        "VITE_CLIENT_ID": "{{ .Values.keycloak.client }}",
      }