apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository}}{{ tpl .Values.image.name . }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: {{ .Values.mountPath }}
              name: {{ .Chart.Name }}
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.resources.cpu.limit }}
              memory: {{ .Values.resources.memory.limit }}
            requests:
              cpu: {{ .Values.resources.cpu.request }}
              memory: {{ .Values.resources.memory.request }}
      restartPolicy: Always
      volumes:
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
            defaultMode: 420
